User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executing ViewResult, running view Index.
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 145.5462ms.
Executed ViewResult - view Index executed in 149.29940000000002ms.
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 169.9977ms
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 170.1611ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Request finished in 417.16740000000004ms 200 text/html; charset=utf-8
Request finished in 417.7123ms 200 text/html; charset=utf-8
Request starting HTTP/2.0 GET https://local.sealside/favicon.ico  
Sending file. Request path: '/favicon.ico'. Physical path: 'D:\Dev\Sealside\Sealside.Website\wwwroot\favicon.ico'
Request finished in 69.0997ms 200 image/x-icon
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executing ViewResult, running view Index.
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 52.842800000000004ms.
Executed ViewResult - view Index executed in 55.658100000000005ms.
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 63.0523ms
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 63.4703ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Request finished in 183.476ms 200 text/html; charset=utf-8
Request finished in 183.4923ms 200 text/html; charset=utf-8
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 3.4504ms.
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 4.4025ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Request finished in 7.974900000000001ms 200 text/html; charset=utf-8
Request starting HTTP/2.0 GET https://local.sealside/favicon.ico  
Sending file. Request path: '/favicon.ico'. Physical path: 'D:\Dev\Sealside\Sealside.Website\wwwroot\favicon.ico'
Request finished in 42.1513ms 200 image/x-icon
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 48707.747500000005ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18230571336156053532", Request ID "8000001d-000a-fd00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 48940.787500000006ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 25996.390900000002ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686507052040235", Request ID "8000002c-0006-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 26164.8404ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 13693.7108ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686515641974801", Request ID "80000012-0008-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 13901.317500000001ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 11227.9575ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686528526876676", Request ID "80000005-000b-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 11400.2553ms 500 
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 1.4633ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18230571336156053534", Request ID "8000001f-000a-fd00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 9.6181ms 500 
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 1.2224000000000002ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686507052040237", Request ID "8000002e-0006-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 8.6516ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 12451.2103ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686537116811276", Request ID "8000000d-000d-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 12643.1859ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 35964.7287ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686481282236451", Request ID "80000024-0000-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 36109.125700000004ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 147.598ms.
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 173.3595ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Request finished in 346.1503ms 200 text/html; charset=utf-8
Request starting HTTP/2.0 GET https://local.sealside/favicon.ico  
Sending file. Request path: '/favicon.ico'. Physical path: 'D:\Dev\Sealside\Sealside.Website\wwwroot\favicon.ico'
Request finished in 90.85350000000001ms 200 image/x-icon
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 32182.911900000003ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686498462105629", Request ID "8000001e-0004-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 32475.784300000003ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 37526.7565ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686498462105631", Request ID "80000020-0004-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 37692.3311ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 32.455200000000005ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686481282236455", Request ID "80000028-0000-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 180.4812ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 72.7243ms.
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 1099.9795000000001ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Request finished in 1262.6938ms 200 text/html; charset=utf-8
Request starting HTTP/2.0 GET https://local.sealside/favicon.ico  
Sending file. Request path: '/favicon.ico'. Physical path: 'D:\Dev\Sealside\Sealside.Website\wwwroot\favicon.ico'
Request finished in 39.968900000000005ms 200 image/x-icon
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing ViewResult, running view Index.
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 101.2752ms.
Executed ViewResult - view Index executed in 94.1204ms.
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 1107.4814000000001ms
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 1107.8369ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Request finished in 1278.9451000000001ms 200 text/html; charset=utf-8
Request finished in 1278.9282ms 200 text/html; charset=utf-8
Request starting HTTP/2.0 GET https://local.sealside/favicon.ico  
Sending file. Request path: '/favicon.ico'. Physical path: 'D:\Dev\Sealside\Sealside.Website\wwwroot\favicon.ico'
Request finished in 49.3459ms 200 image/x-icon
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/favicon.ico  
Sending file. Request path: '/favicon.ico'. Physical path: 'D:\Dev\Sealside\Sealside.Website\wwwroot\favicon.ico'
Request finished in 87.8511ms 200 image/x-icon
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
An error occurred using the connection to database 'usersdb' on server '(localdb)\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. Не удалось получить путь к данным локального приложения. Вероятнее всего, не загружен профиль пользователя. Если экземпляр LocalDB выполняется под управлением IIS, проверьте, включена ли загрузка профиля для текущего пользователя.
)
 ---> System.ComponentModel.Win32Exception (0x89C50120): Unknown error (0x89c50120)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:-1983577824,State:0,Class:20
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 31102.4072ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686507052040195", Request ID "80000004-0006-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 31318.428200000002ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "usersdb" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\Sealside'.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:bd6d0003-5fe7-4542-8f19-7b534bc1e5a6
Error Number:4060,State:1,Class:11
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 11365.484900000001ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686515641974787", Request ID "80000004-0008-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 11483.919ms 500 
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "usersdb" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\Sealside'.
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:bd6d0003-5fe7-4542-8f19-7b534bc1e5a6
Error Number:4060,State:1,Class:11
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 46.946600000000004ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686481282236419", Request ID "80000004-0000-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 52.6878ms 500 
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "usersdb" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\Sealside'.
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:bd6d0003-5fe7-4542-8f19-7b534bc1e5a6
Error Number:4060,State:1,Class:11
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 15.7993ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686481282236421", Request ID "80000006-0000-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 20.9139ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "usersdb" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\Sealside'.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:79b900fc-2383-4c99-91c4-8ae0a60b3048
Error Number:4060,State:1,Class:11
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 22627.017900000003ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18158513750708060161", Request ID "80000002-000c-fc00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 22781.622900000002ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "usersdb" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\Sealside'.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:56586612-b9ab-4137-9644-2275c866ec4e
Error Number:4060,State:1,Class:11
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "usersdb" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\Sealside'.
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:56586612-b9ab-4137-9644-2275c866ec4e
Error Number:4060,State:1,Class:11
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "usersdb" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\Sealside'.
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:56586612-b9ab-4137-9644-2275c866ec4e
Error Number:4060,State:1,Class:11
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "usersdb" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\Sealside'.
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:56586612-b9ab-4137-9644-2275c866ec4e
Error Number:4060,State:1,Class:11
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "usersdb" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\Sealside'.
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:56586612-b9ab-4137-9644-2275c866ec4e
Error Number:4060,State:1,Class:11
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 113824.7114ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686498462105605", Request ID "80000006-0004-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 113984.948ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
System.ArgumentException: Keyword not supported: 'pasword'.
   at Microsoft.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at Microsoft.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 6965.7167ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686519936942085", Request ID "80000006-0009-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 7121.0232000000005ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - С обоих концов канала отсутствуют процессы.)
 ---> System.ComponentModel.Win32Exception (233): С обоих концов канала отсутствуют процессы.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:8f5f222e-d04d-44ec-a689-7ab0318a546e
Error Number:233,State:0,Class:20
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 30805.6594ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18158513750708060163", Request ID "80000004-000c-fc00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 30952.9267ms 500 
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - С обоих концов канала отсутствуют процессы.)
 ---> System.ComponentModel.Win32Exception (233): С обоих концов канала отсутствуют процессы.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:a8f19a75-26f0-44ca-86b7-ebf530c9431e
Error Number:233,State:0,Class:20
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 37710.4557ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686485577203715", Request ID "80000004-0001-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 37869.4224ms 500 
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
An error occurred using the connection to database 'usersdb' on server 'DESKTOP-LGO52NN\LOCALINSTANCE'.
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "usersdb" requested by the login. The login failed.
Login failed for user 'sealside'.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:ae32757d-5b19-4493-a6c9-8bb55c5465c8
Error Number:4060,State:1,Class:11
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 27773.4581ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18158513750708060165", Request ID "80000006-000c-fc00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 27787.884700000002ms 500 
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Users] AS [u]) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
Failed executing DbCommand (50ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Users] AS [u]) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): The SELECT permission was denied on the object 'Users', database 'usersdb', schema 'dbo'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:7c1e85d3-3e8c-4831-9090-7238eb3ca4aa
Error Number:229,State:5,Class:14
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 5335.382500000001ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18230571336156053509", Request ID "80000006-000a-fd00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 5359.8557ms 500 
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Users] AS [u]) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
Failed executing DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Users] AS [u]) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
An exception occurred while iterating over the results of a query for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): The SELECT permission was denied on the object 'Users', database 'usersdb', schema 'dbo'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:7c1e85d3-3e8c-4831-9090-7238eb3ca4aa
Error Number:229,State:5,Class:14
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 2507.3948ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686515641974789", Request ID "80000006-0008-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 2527.0666ms 500 
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Users] AS [u]) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 99.3994ms.
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 285.23290000000003ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Request finished in 331.55330000000004ms 200 text/html; charset=utf-8
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 84.14880000000001ms.
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 1768.1488000000002ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Request finished in 1945.7597ms 200 text/html; charset=utf-8
Request starting HTTP/2.0 GET https://local.sealside/favicon.ico  
Sending file. Request path: '/favicon.ico'. Physical path: 'D:\Dev\Sealside\Sealside.Website\wwwroot\favicon.ico'
Request finished in 55.520900000000005ms 200 image/x-icon
User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-1055182490-990126238-2527702304-827124010-205588594\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Users] AS [u]) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
Executing DbCommand [Parameters=[@p0='?' (Size = 4000), @p1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Users] ([Email], [Name])
VALUES (@p0, @p1);
SELECT [Id]
FROM [Users]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
Failed executing DbCommand (71ms) [Parameters=[@p0='?' (Size = 4000), @p1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Users] ([Email], [Name])
VALUES (@p0, @p1);
SELECT [Id]
FROM [Users]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
An exception occurred in the database while saving changes for context type 'Sealside.Models.Database.UserDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Id', table 'usersdb.dbo.Users'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:d7bfe404-d91f-4ab3-94e6-d45b5a276329
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 36086.4686ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Connection ID "18374686545706745861", Request ID "80000006-000f-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Request finished in 36280.060300000005ms 500 
Request starting HTTP/2.0 GET https://local.sealside/  
Executing endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Sealside.Website.Controllers.HomeController (Sealside.Website).
Entity Framework Core 3.1.3 initialized 'UserDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Users] AS [u]) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
Executing DbCommand [Parameters=[@p0='?' (Size = 4000), @p1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Users] ([Email], [Name])
VALUES (@p0, @p1);
SELECT [Id]
FROM [Users]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
Executing DbCommand [Parameters=[@p0='?' (Size = 4000), @p1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Users] ([Email], [Name])
VALUES (@p0, @p1);
SELECT [Id]
FROM [Users]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
Executing ViewResult, running view Index.
Executed ViewResult - view Index executed in 62.339800000000004ms.
Executed action Sealside.Website.Controllers.HomeController.Index (Sealside.Website) in 210.3852ms
Executed endpoint 'Sealside.Website.Controllers.HomeController.Index (Sealside.Website)'
Request finished in 226.5138ms 200 text/html; charset=utf-8
Request starting HTTP/2.0 GET https://local.sealside/favicon.ico  
Sending file. Request path: '/favicon.ico'. Physical path: 'D:\Dev\Sealside\Sealside.Website\wwwroot\favicon.ico'
Request finished in 40.1453ms 200 image/x-icon
